### PR TITLE
Add optional parameters to ImageManager::findAll

### LINKED ISSUE #97: List images dangling filter
We should allow the `dangling` filter..see http://docs.docker.com/reference/api/docker_remote_api_v1.16/#list-images

Will work on this soon.

### PR DESCRIPTION
**Pull request by hacfi**
Allows `$imageManager->findAll(['all' => true]);` and `$imageManager->findAll(['dangling' => true]);`

See http://docs.docker.com/reference/api/docker_remote_api_v1.17/#list-images

Fixes #97

### CODE REVIEW

**Comment by ubermuda** [comment]
tests + docs :)

also (maybe that's not the right place to talk about it, but) it feels like docker-php is becoming more and more a low level PHP abstraction of the API, instead of the high level php-minded library I had in mind. That's not necessarily a bad thing, but I'm starting to think maybe we could have a plumbing layer that's basically a 1:1 mapping of the Remote API, and a porcelain layer that's more high level and that make common operations easier. What do you think?

**Comment by hacfi** [comment]
@ubermuda I was afraid that would be requested ;)! Will add them later this week!

**Comment by ubermuda** [comment]
It's easy to make tests mandatory when you're not the one writing them :D

**Comment by hacfi** [comment]
@ubermuda Tests added.

Docs are included in a different PR as I wanted to clean this up anyway (as previously discussed).

I like the idea of separating the implementation of the Remote API and the easy-to-use everyday use cases. My approach would be to aim for 100% API implementation (see #30) and when we get close start the separation. I think the low level PHP abstraction is important to make more advanced users happy and as far as I know this is the only Docker library for PHP. We shouldn’t give anyone a reason to start another one :).

**Comment by hacfi** [comment]
One test failed because of `Docker\Exception\APIException: No such image: ubuntu:precise (tag: precise)`. Maybe we should change the tests so it doesn’t depend on the Docker registry which seems unstable from Travis but it’s a normal use-case.

**Comment by hacfi** [comment]
Or try to run the tests twice or pull the required images before starting the tests.

**Comment by joelwurtz** [comment]
Do we really need a ubuntu image for our tests, a busybox should be enough ?

**Comment by joelwurtz** [comment]
Otherwise for the pull request, i'm not a fan of passing an array of parameters, it is not better to declare each parameter available for the findAll method

```
public function findAll($dangling = false, $all = false)
``` 

So people does not need to go to docker documentation as we can explain each parameters available and their purpose (but it's more maintenance work on our side)

**Comment by hacfi** [comment]
@joelwurtz I’ll check but we can definitely make it work with busybox.

Will update the PR. In this case I prefered an array (we wouldn’t have to update the code if another filter gets added) but individual parameters make it easier for other developers. Does the name findAll still make sense or should we adapt it? Or rename `find` to `findImage`?

**Comment by joelwurtz** [comment]
LGTM ping @ubermuda

**Comment by ubermuda** [comment]
Thanks!

**Pull request merged**
