### PR TITLE
Rename ImageManager::delete to ImageManager::remove to be more consistent

### LINKED ISSUE #85: Method name inconsistency: ImageManager::delete
Should we rename it to remove and keep delete as an alias for now?

### PR DESCRIPTION
**Pull request by hacfi**
...with the Docker API.

Fixes #85

### CODE REVIEW

**Comment by hacfi** [comment]
@ubermuda Good to merge?

**Comment by ubermuda** [comment]
Yes!

**Comment by ubermuda** [comment]
Thanks!

**Comment by hacfi** [comment]
Nice..thanks!

**Pull request merged**
