### PR TITLE
Update link to Docker docs into README

### PR DESCRIPTION
**Pull request by maxvyaznikov**
There was incorrect link. Just fixed

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks, I noticed there's another link to docker.io on line 4 that also should be changed to docker.com

**Comment by hacfi** [comment]
:+1: thanks for the PR

**Comment by ubermuda** [comment]
Thank you @maxvyaznikov

**Comment by ubermuda** [comment]
And thanks @thaJeztah, I've fixed this too

**Comment by thaJeztah** [comment]
Thanks @maxvyaznikov!

**Pull request merged**
