### PR TITLE
[WIP] Add documentation on read the docs

### PR DESCRIPTION
**Pull request by joelwurtz**
Work in progress on the documentation:

* Use readthedocs (for versioning purpose)
* Separate Container / Image concept
* Add some cookbooks on how to do A ?, how to do B ? ....

This branch is currently building at: http://docker-php.readthedocs.org/en/feature-readthedocs (manual trigger for the moment)

ping @ubermuda :)

### CODE REVIEW

**Comment by hacfi** [comment]
Personally I prefer Markdown as a lot of users will read the docs on Github and on their computers.

Once this PR is merged I’ll go over the code and add some documentation so we cover almost all the features in the docs. Then I’ll see if I have time to work on the missing features listed in #30

**Comment by hacfi** [comment]
I will include a document showing the status of the implementation. It will look like https://gist.github.com/hacfi/bec2ebdfd34d4b8c5cea but including the status (like done, n/a yet, irrelevant) and a link to the correct doc to explain the usage.

**Comment by ubermuda** [comment]
Is there still not a way for multiple people to contribute on the same PR?

**Comment by hacfi** [comment]
Maybe I can create a PR on @joelwurtz feature/readthedocs branch but might be easier to just merge and then go from there!?

**Comment by ubermuda** [comment]
Yeah I was thinking of the later

**Pull request merged**
