### PR TITLE
Fix Travis builds (making Docker run again and actually use Symfony version)

### PR DESCRIPTION
**Pull request by hacfi**
After @joelwurtz already tried several ways to fix docker on the `fix/travis` branch I’m giving it a shot too.

Just some notes:
Travis CI changed the cookbooks which might have caused the issues..compare: https://github.com/travis-ci/travis-cookbooks/compare/5736160...23bb455#commit_comments_bucket

I noticed something REALLY unnecessary: the env matrix isn’t actually used!! This will be fixed later.

### CODE REVIEW

**Comment by hacfi** [comment]
Very good news guys..tests are running again! I hope this is not just because Travis doesn’t seem very busy right now. I’m trying docker 1.5.0 now.

**Comment by hacfi** [comment]
PR is ready:
- using Docker 1.4.1 as 1.5.0 is buggy (created an issue over at docker/docker)
- make use of Symfony Version (until now the multiple tests were useless as all of them installed 2.6 anyway :) )

**Comment by hacfi** [comment]
@ubermuda :)

**Comment by joelwurtz** [comment]
:o nice !

**Pull request merged**
