### PR TITLE
[Proposal] docker-compose testing

### PR DESCRIPTION
**Pull request by schmunk42**
**Note: This PR is not complete yet, it's primarily a code example atm.**

How about an improved dockerized testing solution? While creating some PRs I also tried to run the tests, but faced some glitches, such as certificate setup and missing images for testing.

The process itself can be improved - for sure. But here's the basic idea: Just run a pre-configured docker container for the tests. 
The image is the [base image](https://github.com/phundament/docker-images/blob/master/phundament/php-one/5.6-7.0/Dockerfile-5.6-fpm) from our PHP app template, but just serves as a PHP cli+composer here - it's also configured to run a PHP app in `/app`.
It would also be possible to run [Codeception](http://codeception.com) tests with this image.

By mounting the `docker.sock` file we can use the docker-client without further configurations.

Feedback appreciated :)

### CODE REVIEW

**Comment by joelwurtz** [comment]
Don't mind have this, can you rebase this, what would be nice is to have have a test image for each env (php 5.4 / 5.5 / 5.6 / 7), so 4 services in the docker compose

**Comment by schmunk42** [comment]
Btw. `docker-compose` also supports env substitution, so we could also use the same stack multiple times.

**Comment by schmunk42** [comment]
Rebased and added PHP 7.0, unfortunately I don't have 5.4 and 5.5 images as they are not fully supported anymore, see the referenced issue above for details (there is no official Docker PHP image with composer for 5.6 and 7.0).

FYI: I also get these errors at the moment, but I can't really figure out the problem...

```
php56_1 | Configuration read from /app/phpunit.xml.dist
php56_1 | 
php56_1 | ..........PHP Fatal error:  Interface 'Http\Client\HttpClient' not found in /app/src/DockerClient.php on line 15
php56_1 | 
php56_1 | Fatal error: Interface 'Http\Client\HttpClient' not found in /app/src/DockerClient.php on line 15
php70_1 | PHPUnit 3.7.38 by Sebastian Bergmann.
php70_1 | 
php70_1 | Configuration read from /app/phpunit.xml.dist
php70_1 | 
php70_1 | ..........PHP Fatal error:  Interface 'Http\Client\HttpClient' not found in /app/src/DockerClient.php on line 14
php70_1 | 
php70_1 | Fatal error: Interface 'Http\Client\HttpClient' not found in /app/src/DockerClient.php on line 14
```

**Comment by joelwurtz** [comment]
composer install ?

**Comment by joelwurtz** [comment]
You can use https://hub.docker.com/r/jolicode/php54/ and https://hub.docker.com/r/jolicode/php55/ for this versions of php

**Comment by schmunk42** [comment]
> composer install ?

My fault, I had an old `composer.lock`.

That's a glitch at the moment, You need to remove `composer.lock`, when you switch the PHP version - I'll think about a solution for that.

I am getting several `Permission denied` on 5.4 and 5.5, but I guess you should have a quick look at those then.

Tests for PHP 5.6 and 7.0 are green.

**Comment by joelwurtz** [comment]
> My fault, I had an old composer.lock.

Oh yes, maybe doing a composer update is better (look at the .travis.yml which does that) since it's a library and the composer.lock is not shared there is no harm by doing that

**Comment by schmunk42** [comment]
Ready from my side so far.

PS: I stumbled upon this project today: https://github.com/omauger/docker-compose-php - might be also of general interest for you guys.

**Comment by joelwurtz** [comment]
Thanks !

Otherwise not a fan of this kind of library which abstract a process command as it's always a mess to configure / setup in different environment and hard to maintain.

**Pull request merged**
