### PR TITLE
fix missing required param 'name' is some imageResource methods

### PR DESCRIPTION
**Pull request by krzaczek**
Some imageManager methods where missing a required name parameter like find(), history(), remove()

### CODE REVIEW

**Comment by joelwurtz** [comment]
Oups :),

Nice catch :+1: Thanks ! will merge as soon as tests are ok !

**Comment by krzaczek** [comment]
Wait found one more

**Comment by joelwurtz** [comment]
BTW any feedback on the generation / write process for the API ?

**Comment by krzaczek** [comment]
I love the JSON description of the API. Been using guzze-service and love it.

**Comment by krzaczek** [comment]
Actually I want to rewrite one of my libraries to use http-plug + jane to get rid of guzzle dependency.

**Comment by krzaczek** [comment]
One more thing but I don't know how to implement it.

```php
$imageManager->find('java:8')
```
Will rentrun 404

```php
$imageManager->find(urlencode('java:8'))
```

Will return 200 

maybe this should be implemented inside the method ?

**Comment by krzaczek** [comment]
Or all parameters with `in` set to `path` should be url encoded

**Comment by joelwurtz** [comment]
parameter value should be urlencoded, yes, it's more a bug for jane-swagger.

**Comment by joelwurtz** [comment]
Thanks !

**Comment by joelwurtz** [comment]
BTW, it's urlencoded now

**Comment by krzaczek** [comment]
Great

**Pull request merged**
