### PR TITLE
Fix image name parsing (allowing repositories with ports).

### PR DESCRIPTION
**Pull request by mycroft**
That PR fixes image name parsing. When using private registries with custom tcp ports, the image name can contain multiple ':', but current code doesn't allow this case. Doing a regexp helps to handle it.

Includes a small unit test.

### CODE REVIEW

**Comment by ubermuda** [comment]
Alright, this covers #129, but in a better way I guess.

The only thing I dislike is that we have the regexp at two places in the code.

Do anyone have any idea of how to handle this with a better design? (poke @hacfi @joelwurtz)

**Comment by mycroft** [comment]
What about 2 new functions in the Image class: A static one to validate/parse the repoTag without instantiating an Image object, and a specific setter for repoTag.

Code would look like:

```php
    /**
     * Validate repoTag format
     *
     * @param string $repoTag The repository/tag to validate
     * @return Array with repository & tag key sets if valid, FALSE if not.
     */
    public static function validateRepoTag($repoTag)
    {
        $ret = preg_match('/^(.*):([^:]*)/', $repoTag, $matches);

        if(1 !== $ret) {
            return FALSE;
        }

        return array(
            'repository' => $matches[1],
            'tag' => $matches[2]);
    }

    /**
     * Set repository / tag if repoTag is valid
     *
     * @param string $repoTag The repository/tag to set to the image.
     * @return boolean TRUE is valid & set, FALSE if not.
     */
    public function setRepoTag($repoTag)
    {
        $parsedRepoTag = $this->validateRepoTag($repoTag);
        if(FALSE === $parsedRepoTag) {
            return FALSE;
        }

        $this->setRepository($parsedRepoTag['repository']);
        $this->setTag($parsedRepoTag['tag']);

        return TRUE;
    }
```

Does that seem better?

**Comment by ubermuda** [comment]
It is not ideal, but it is better :) Except:

1. the CS is all fucked up in your examples
2. your `validateRepoTag` does not really validate but parse the image name, so I'd name it `parseRepoTag`

**Comment by joelwurtz** [comment]
How about throwing an exception instead of returning false ? (Really don't like the true / false return here as it's hard to use from an user point of view)

**Comment by darkwinternight** [comment]
Throwing exceptions is almost *always* the better choice.

**Comment by ubermuda** [comment]
Merged in 49f5c7f9dc0824235f17116fcdf85888e129b9c5

**Pull request closed without merging**
