### PR TITLE
Allow to push image

### PR DESCRIPTION
**Pull request by sroze**
This PR add a `push` method on the image manager that allows to push an image to a registry.

### CODE REVIEW

**Comment by hacfi** [comment]
Is the `X-Registry-Auth` header really required?

**Comment by sroze** [comment]
@hacfi yes, it is.

**Comment by hacfi** [comment]
Haven’t tried this but looks good to me!

@sroze Will this work with both Docker Hub and private registries?

**Comment by sroze** [comment]
@hacfi it is, for private repositories you have have to have an image name like `address.of.my.repository:1234/image-name` so Docker will know it have to push to `address.of.my.repository:1234`.

**Comment by sroze** [comment]
ping @hacfi

**Comment by hacfi** [comment]
Looks good to me but I can’t merge it as I’m just a contributor.

**Comment by tasuk** [comment]
@ubermuda, @joelwurtz: Pretty please!

**Comment by ubermuda** [comment]
Hey @sroze, thanks for your contribution! Can you rebase this on master? I just merged in some fixes to unit test running in travis

**Comment by sroze** [comment]
@ubermuda I did but still failing, without any relation with this PR.

**Comment by ubermuda** [comment]
That's right, I'll have to take a look at this later :)

**Comment by sroze** [comment]
Thanks @ubermuda ! Anyway you can release a minor version ?

**Comment by ubermuda** [comment]
Yup, just pushed tag v0.4.2

**Pull request merged**
