### PR TITLE
update request excpetion to show message

### PR DESCRIPTION
**Pull request by schmunk42**
I got several empty error messages, like:

```
Exception 'Docker\Exception\APIException' with message ''
```

With this change you get:

```
Exception 'Docker\Exception\APIException' with message 'Client error response [url] /containers/bcb617efada6/logs?follow=0&stdout=0&stderr=0&timestamps=0&tail=all [status code] 400 [reason phrase] Bad Request'
```

### CODE REVIEW

**Comment by joelwurtz** [comment]
Can we use the exception message only if the content of the body is empty ?

In fact this was the old use case but errors was not really significant (as it's a curl / guzzle errors) having this allow to display the docker error if available.

**Comment by schmunk42** [comment]
Like so?

    $msg = !empty($e->getResponse()->getBody()->__toString()) ? $e->getResponse()->getBody()->__toString() : $e->getMessage();
    throw new APIException($msg, $e->getRequest(), $e->getResponse(), $e);

**Comment by joelwurtz** [comment]
More like this : 

```php
$message = trim($e->getResponse()->getBody()->__toString());

if (empty($message)) {
     $message = $e->getMessage();
}

throw new APIException($message, $e->getRequest(), $e->getResponse(), $e);
```

The point is to avoid an empty message, as $e->getResponse()->getBody()->__toString() will be empty on the second call because the stream will be fully ready

**Comment by schmunk42** [comment]
Yeah, you're right about the trim. I remember getting a string with dozens of spaces.

**Comment by joelwurtz** [comment]
awesome :heart:

**Pull request merged**
