### PR TITLE
Docs: Improve installation, add image pull, small changes

### PR DESCRIPTION
**Pull request by hacfi**
Working on the docs..feedback more than welcome!

More usage examples are coming over the next few days

### CODE REVIEW

**Comment by joelwurtz** [comment]
:heart:

**Comment by hacfi** [comment]
@joelwurtz Would you mind if I don’t put each "feature" in a separate document but combine the method of the ImageManager and ContainerManager so developers don’t have to click around so much to find the info?

**Comment by Boran** [comment]
Could this stuff be merge in? I have several api examples that I could add too.
I also have a list of tested docker api examples with curl, I think they are essential in understanding.. Maybe a separate doc file for those "docker_api.md" ?

**Comment by hacfi** [comment]
Yes, let's merge them & I'll create a new PR when I work on the docs again.

**Comment by ubermuda** [comment]
BOUME

**Pull request merged**
